<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.Web.Extensions" />
    <Reference Include="com.rlabrecque.steamworks.net">
      <HintPath>G:/SteamLibrary/steamapps/common/RimWorld/RimWorldWin64_Data/Managed/com.rlabrecque.steamworks.net.dll</HintPath>
      <Private>True</Private>
    </Reference>
  </ItemGroup>
</Project>
