namespace MapGenAI.MapGen
{
    // Natural layouts and older exact recipes share the normal single-request edit pipeline.
    public static class LandformPrompt
    {
        public static string Rules(bool korean) => CompositionRules(korean)+NaturalRules(korean)+LegacyRules(korean);
        public static string Rules(bool korean,bool hasSavedLandforms) => CompositionRules(korean)+(hasSavedLandforms?NaturalRules(korean):"")+LegacyRules(korean);
        public static string SavedRules(bool korean) => NaturalRules(korean);
        static string CompositionRules(bool korean) => korean ? @"
공통 자연풍경 구성 (새 자연스러운 풍경과 추천의 우선 도구):
- 분지/골짜기/산기슭 세 가지 정형만 고르지 마세요. 기존 composite의 공통 영역과 곡선으로 산 없는 호숫가, 열린 구릉, 비대칭 능선, 연결된 빈터 등 서로 다른 구도를 설계합니다. 타일의 기존 풍경을 바탕으로 필요한 부분만 조정하고, 평지·주요 지형·작은 요소의 역할과 관계를 먼저 정합니다. 큰 도형을 지도 전체에 덮지 않습니다.
- shapes의 새 prim:path는 verts 2..12개의 순서 있는 좌표와 w(전체 폭 .008.. .7)를 받는 부드러운 곡선 영역입니다. 폐곡선이 아니며 끝도 둥글게 연결됩니다. 3..6개 점으로 큰 굽음을, edge_roughness:medium으로 작은 윤곽 변화를 표현합니다. 산 능선은 compose e:0.9~1.2, 넓은 자연 평지는 e:0.05와 fill 생략, 길쭉한 물은 fill:WaterShallow와 e:0.05로 같은 도구를 사용합니다. 정확한 도로는 road_ops, 지정 칸 폭의 마른 통로는 passage를 계속 사용합니다.
- 서로 다른 역할은 각각 top-level ID로 만듭니다. 물·산·평지를 같은 ID에 섞지 마세요. 필요한 경우 타원/다각형/path를 union하여 윤곽을 구성하되 새 전체 풍경은 보통2~6개 영역으로 절제합니다. 산이 없어도 좋은 구도를 만들 수 있습니다. 정확한 원/별/하트 요청과 기존 저장된 landform은 이전 방식을 유지합니다.
- '넓은 정착 평지/마른 땅'을 명시한 전체 풍경은 그 생활 공간도 fill 없는 별도 평지 ID로 계획하세요. 그래야 이후 '그 평지 가장자리로 연못을 옮겨'라는 요청에서 관계를 유지할 수 있습니다. 세계 지면 전체를 흙으로 덮지 않습니다. 기존 자연 평지를 막연히 지칭한 후속에 기준 ID가 없으면 원하는 방향을 짧게 확인하고, 없는 기준 ID를 만들었다고 주장하지 마세요.
- composite에도 details:natural/none, variant:0..999999를 지원합니다. 자연 평지와 물 영역에는 details:natural을 명시하세요. 물 영역 밖 최대 6칸의 육지에도 좁고 끊어진 물가를 만듭니다. 해당 바이옴에 진흙이 있고 기후와 원래 토양이 맞을 때만 일부 진흙을 쓰며 사막은 모래·자갈을 우선합니다. 실제 물·산·도로·특수 지면·비율 채움은 보존합니다. '자동 바닥·식생 조화 효과만 꺼 줘'는 효과가 켜진 기존 ID의 details:none만 수정합니다. 다시 켜기는 details:natural이며 형상·다른 설정은 유지합니다. variant는 새 후보의 윤곽 변주이며 후속 편집에서는 유지하세요. 물 추가나 전역 비옥도 보너스를 뜻하지 않습니다.
- composite의 anchor:다른영역ID, placement:inside|edge|beside는 매 생성마다 실제 기준 영역에 맞춰 전체 영역을 옮깁니다. inside=완전히 안쪽, edge=안쪽 가장자리, beside=바깥에 인접. direction:left/right/top/bottom/대각 방향으로 원하는 쪽을 지정할 수 있습니다. 기준은 먼저 그린 산/평지/물 자체의 mask이며, landform이면 평지 mask입니다. 닫힌 고리의 빈 구멍은 mask가 아니므로 그곳의 별도 평지 ID를 기준으로 삼으세요. 월드 강/해안을 임의 ID로 참조하지 않습니다.
- 자동 배치할 도형의 원래 좌표는 중앙[.5,.5] 부근의 작은 형상으로 정의하세요. 전체 윤곽과 feather를 감싼 직사각형이 들어가야 하며 공간 부족 시 크기를 줄이거나 관계를 수정해야 합니다. 같은 기준을 따르는 요소는 서로 겹치지 않게 배치합니다. 안쪽 작은 연못은 평지보다 충분히 작게(예: w .10,h .07,f .008), 중앙 정착 공간을 남기려면 placement:edge를 쓰세요.
- 예: 넓은 자연 평지에 {""id"":""pond"",""type"":""composite"",""anchor"":""clearing"",""placement"":""edge"",""direction"":""right"",""edge_roughness"":""medium"",""shapes"":[{""id"":""p"",""prim"":""ellipse"",""center"":[.5,.5],""w"":.10,""h"":.07}],""compose"":[{""op"":""add"",""s"":""p"",""e"":.05,""f"":.008,""fill"":""WaterShallow""}]}를 연결합니다. 출력 JSON의 숫자는 0.5처럼 정규형을 쓰세요. 기준 평지를 옮기면 연못도 따라갑니다. 붙어있는 연못의 위치는 direction/placement로 바꾸며 absolute move는 anchor와 placement를 둘 다 null로 해제한 뒤 사용합니다.
- 기준 영역 삭제는 종속 영역도 명시적으로 제거/재연결하고, 관계를 유지하는 평지 확대는 그 ID의 형상만 수정합니다. 재료/비율만 변경하면 형상과 관계는 그대로 둡니다. 70% 비옥토는 평지 ID를 region_fill/inside로 참조합니다.
" : @"
Shared natural landscape composition (preferred for NEW natural scenery and recommendations):
- Compose different layouts from common areas and curves, rather than choosing only basin/valley/foothills. Keep the native biome terrain as the foundation and change only needed areas. Plan usable space, main terrain and restrained accents in relation to each other. A beautiful open lakeside does not need mountains.
- composite shapes support prim:path, verts with 2..12 ordered normalized control points, w = full width .008.. .7. It is an open smooth curve with rounded ends, not a polygon. Use 3..6 points for broad bends and edge_roughness:medium for small irregularity. The same path makes ridges (compose e:.9..1.2), natural open ground (e:.05, omit fill), or elongated shallow water (fill:WaterShallow,e:.05). Keep road_ops for actual roads and passage for exact cell-width dry access.
- Give each logical mountain, plain and water area a separate top-level ID. Combine ellipse/poly/path primitives as needed, normally 2..6 areas for a complete landscape. Keep exact circles/stars/hearts and existing saved landforms on their existing paths.
- When a full landscape explicitly asks for broad dry/buildable settlement space, represent that space with a separate unpainted floor ID so later requests can refer to its edge. Do not repaint the whole map. If a later request ambiguously refers to native open ground with no authored source ID, ask a short directional clarification instead of inventing an existing reference.
- composite also accepts details:natural|none and persisted variant:0..999999. Include details:natural on natural floor AND water areas. Narrow, interrupted dry-side banks may extend up to 6 cells outside the water area's mask. Small mud patches require native biome support, warm wet climate and existing soil; desert/sandy banks use sand/gravel. Actual water, rock, roads, special ground and whole counted-fill areas stay protected. 'Turn off only automatic ground/vegetation blending' changes only details:none on existing enabled IDs; re-enable with natural, keeping geometry and all other settings. Vary variant for new contours, preserve it on edits. This does not add water or global bonuses.
- composite anchor:areaID with placement:inside|edge|beside persists a relationship resolved against the actual generated source mask: fully inside, inside near its edge, or adjacent outside. Optional direction:left/right/top/bottom/diagonals selects a side. Source composite masks are the areas themselves; landform masks are their floor. A closed ring's hole needs its separate floor ID, not the rock-ring ID. Do not invent IDs for world rivers/coasts.
- Define the attached shape as a small shape around [.5,.5]. Its complete feathered bounding rectangle must fit; failure requires resizing or changing the relationship. Siblings sharing an anchor avoid each other. For a small pond leaving central settlement space, use edge, e.g. ellipse w:.10,h:.07 with f:.008. Moving its source makes it follow. Edit direction/placement to reposition an attached area; clear BOTH anchor and placement with null before absolute move.
- Remove/rebind dependent areas when removing a source. Preserve geometry/relationships on material edits. Use region_fill with the plain ID/inside for an exact 70% soil fill. Never repaint native biome ground just to make it flat.
";
        static string NaturalRules(bool korean) => korean ? @"
기존 자연지형 호환 도구 (새 풍경은 위 공통 조합 우선, 기존 편집은 이 계약 유지):
- 새 자연 분지·넓은 굽은 골짜기·산기슭 평야는 type:landform으로 만들 수 있습니다. 산줄기와 연결된 내부 평지를 코드가 함께 생성합니다. 단순 원/별/하트, 닫힌 도넛/칼데라, 지정 폭의 좁은 협곡은 기존 도형/통로를 사용하세요. 기존 composite 지형을 요청 없이 새 방식으로 교체하지 마세요.
- landform:open_basin(열린 비대칭 분지), winding_valley(넓고 굽은 골짜기), foothills(한쪽 산줄기의 가지와 이어지는 평야). direction은 분지 출구 방향, 계곡 축 방향, 산기슭의 산이 있는 방향입니다. 허용: left/right/top/bottom/대각 방향 또는 각도. position:[x,z] 기본 중앙. size는 전체 규모: small=.55, medium=.75, large=.95 또는 .35..1, 기본 .9.
- 새 지형은 shape_ops add를 사용하세요. layout:organic이 기본이며 서로 다른 크기의 능선·옆 골짜기·불규칙한 산벽을 자동으로 만듭니다. 사용자가 세부 윤곽을 일일이 지정할 필요가 없습니다. 전체 elevation_shapes 배열로 새 지형을 보낼 때는 layout:organic을 명시하세요. 기존에 저장된 layout 생략/classic은 이전 모양을 유지합니다. 단순 위치/폭 수정 때 layout은 유지하고, 기존 자연지형을 더 유기적으로 다듬어달라는 요청에만 organic으로 변경합니다.
- 새 landform add는 details:natural도 기본입니다. 실제 물가와 산기슭의 일반 흙/모래에 작고 불규칙한 모래/자갈 경계를 더하고, 해당 바이옴의 초기 식생 밀도에 변화를 줍니다. 물·높이·명시적 채움/비율/도로·기존 자갈/특수 지형은 보존합니다. 사막·랜드마크의 특수 식생과 이후 재성장은 기본 게임 규칙입니다. 전체 배열로 새 자연지형을 보내면 details:natural도 명시하세요. 기존 저장의 details 생략/none은 자동 변경하지 않습니다. 주변 지면/식생을 조화시켜달라는 요청에만 기존 ID의 details를 natural로 바꾸며, 끄기는 none입니다. 단순 위치/폭 수정은 이 값을 유지하세요.
- details는 주변 연결 효과이며 새 물이나 특징을 만드는 설정은 아닙니다. 그러나 빈 설정에서 '자연스러운 열린 분지 만들어 줘', '정착하기 좋은 골짜기'처럼 전체 풍경을 맡긴 요청은 지형 하나만 찍으라는 뜻이 아닙니다. 첫 응답에서 주된 landform과 타일에 어울리는 작은 요소를 함께 구성하세요. 물이 없는 온대림/초원 등에는 한쪽 평지의 작고 얕은 불규칙한 연못을 고려하고, 원래 강/해안/호수가 있으면 그것을 우선 활용하세요. 건조 지형·물 제외·산만 요청에는 물을 덧붙이지 않습니다. 추가 요소는 0~2개로 절제하고 중앙 정착지와 출구를 비워 두세요. 물은 산 배치 다음에 별도 composite/fill:WaterShallow로 작은 비대칭 윤곽을 명시할 수 있습니다. 실제 강/해안 연결을 발명하지 마세요.
- 새 landform의 평지는 기존 바이옴 지면을 사용합니다. 초원/특수 모드 토양을 Soil 또는 SoilRich 원판으로 덮지 마세요. 명시적으로 토양 변경을 요청한 경우만 재료/비율 채움을 추가합니다. 후속 위치/폭/출구/효과 켜기·끄기 요청에는 물·특징·전역 비옥도/식생/동물 보너스를 추가하지 마세요. Map Preview는 바닥만, 실제 풀/나무는 완성 맵에서 확인합니다. 식생/재료의 정확한 수량이나 영구 군락을 약속하지 마세요.
- '자동 바닥·식생 조화 효과만 꺼 줘'는 details:natural인 기존 landform/composite ID에 shape_ops update changes:{""details"":""none""}만 적용합니다. 다시 켜기는 details:natural입니다. 산/연못 형상·다른 설정은 유지합니다. 모든 ID의 details가 생략/none이면 이미 효과가 꺼져 있다고 설명하고, 지형을 몰래 교체하지 마세요.
- gap은 사용 가능한 평지의 폭을 조절합니다(.1.. .32). 기본 분지/산기슭 .25, 계곡 .14. 커질수록 내부가 넓어집니다. 분지의 opening은 출구 폭이며 .08.. .3, 기본 .14. gap을 넓힐 때 출구 폭은 그대로 둡니다. variant는 정수0..999999(기본0)이며 새 후보의 다른 산줄기 배치를 원하면 바꾸고 후속 편집에서는 유지합니다. strength/fill/edge_roughness/compose는 여기에 사용하지 않습니다. opening:null은 기본 출구 폭으로 복원합니다. 다른 종류로 바꾸면 이전 분지의 출구 폭은 자동 해제됩니다.
- 예: {""shape_ops"":[{""op"":""add"",""shape"":{""id"":""basin"",""type"":""landform"",""landform"":""open_basin"",""direction"":""bottom"",""size"":0.9,""variant"":23}}]}.
- '안쪽 평지만 넓혀'는 같은 ID의 gap만 증가, '출구를 남쪽으로'는 direction, '출구만 넓혀'는 opening, 전체 이동은 shape_ops move, 전체 크기는 size만 변경합니다. 연결된 평지와 산줄기가 함께 따라갑니다. 분지의 direction은 산벽을 유지하고 출구만 옮깁니다. 골짜기/산기슭의 direction은 전체 방향입니다.
- 이 ID의 region_part:inside는 산이 아니라 생성한 평지입니다. '안쪽70%비옥토'는 region_fill(region:그ID,region_part:inside,coverage:0.7,fill:rich_soil), 폐허도 region:그ID/inside를 참조합니다. 열린 지형이므로 enclosed는 금지. 이 지형 삭제 때 그 영역을 참조하는 채움/구조물도 처리합니다. 물·도로·건물 등 보호 대상은 기존 규칙을 따르며 모든 바닥을 흙으로 칠하지 않습니다.
- 추천에서 타일/취향에 어울리는 경우만 사용하고 세 종류를 고정 세트로 추천하지 마세요. 기존 산·강·해안·특징과 타일 조건을 반영하세요. 강 없는 타일에 실제 강/해안을 새로 만들거나 기존 물/특징을 지워 맞추지 마세요. 추가 LLM 호출은 필요 없습니다.
" : @"
Existing natural layout tools (prefer shared composition for new scenery; preserve this contract when editing saved landforms):
- New natural open basins, broad winding valleys and foothill plains may use type:landform. Code generates related ridges and connected usable ground. Keep existing exact shapes for circles/stars/hearts, closed donuts/calderas, and passages for narrow canyons with specified cell widths. Never replace existing composite geometry without a request.
- landform is open_basin, winding_valley or foothills. direction specifies the basin opening, valley axis, or mountain side of the foothills. Use left/right/top/bottom/diagonals or degrees. position:[x,z] defaults to center. size is overall scale: small=.55, medium=.75, large=.95 or .35..1, default .9.
- Create new layouts with shape_ops add: layout:organic is the default, composing unequal rounded shoulders, side gullies and irregular walls without detailed user instructions. Explicitly set layout:organic if sending a new landform in the full elevation_shapes array. Missing/classic layout in stored terrain preserves its previous geometry. Preserve layout on ordinary moves/width edits; upgrade existing natural terrain to organic only when asked to make it more organic.
- New landform adds also default to details:natural. Small irregular sand/gravel banks follow actual water and rock edges on ordinary soil/sand, with local variation in initial biome vegetation. Water, heights, explicit fills/coverage/roads, existing gravel and special terrain are preserved. Deserts, landmark-specific vegetation and later regrowth retain native rules. Explicitly include details:natural for new full-array layouts. Missing/none in stored layouts stays unchanged; enable natural only when asked to blend the existing ground/vegetation, disable with none, and preserve it on ordinary moves/width edits.
- Details blends existing edges; it does not create water/features. However, on an empty layout, a short request such as 'make a natural open basin' or 'a pleasant valley to settle in' delegates a complete landscape, not just one isolated shape. In that first response compose the main landform with restrained tile-appropriate accents. On a temperate forest/grassland tile without water, consider one small shallow irregular pond to one side of the floor; prefer an existing river/shore/lake when present. Add no water to a dry landscape, a no-water request or a mountains-only request. Use 0..2 accents and leave the central settlement space and exit open. Add water after the landform, using a separate small asymmetric composite with fill:WaterShallow. Never invent world river/coast connections.
- New landform floors retain biome ground. Do not repaint grassland or modded soil with a Soil/SoilRich disk. Add a material/coverage fill only when requested. On follow-up moves, width/exit edits or detail toggles, add no water/features or global fertility/vegetation/animal bonuses. Map Preview shows ground; actual grass/trees need the full map. Do not promise exact vegetation counts or permanent clusters.
- 'Turn off only the automatic ground/vegetation blending' updates ONLY details:none on existing landform/composite IDs with details:natural via shape_ops. Turning it back on uses details:natural. Preserve mountain/pond geometry and all other settings. If all IDs have missing/none details, explain that blending is already off; do not silently replace that terrain.
- gap controls usable floor width (.1.. .32); defaults basin/foothills .25, valley .14. Larger widens the floor. open_basin alone accepts opening (.08.. .3, default .14), independently controlling exit width. variant is a persisted integer0..999999(default0); vary it for a new layout, preserve it on follow-ups. Do not supply strength/fill/edge_roughness/compose. opening:null restores the default exit width; switching away from open_basin automatically clears its previous opening override.
- Example params: {""shape_ops"":[{""op"":""add"",""shape"":{""id"":""basin"",""type"":""landform"",""landform"":""open_basin"",""direction"":""bottom"",""size"":0.9,""variant"":23}}]}.
- Widen only the interior by updating gap on the existing ID; opening direction via direction, exit width via opening; move the whole layout using shape_ops move, resize using size. Floor and ridges follow together. For a basin, direction moves only the exit while retaining the walls. For valleys/foothills it sets the whole layout orientation.
- region_part:inside on this ID means its planned FLOOR, not the mountain. A 70% rich-soil interior uses region_fill(region:thatID,region_part:inside,coverage:0.7,fill:rich_soil); positioned ruins reference thatID/inside too. Never use enclosed for these open layouts. Handle dependent fills/structures on deletion. Existing protected water/roads/buildings rules still apply. Do not paint the entire floor with soil.
- Recommend these only when appropriate to the tile/preferences, never as a fixed trio. Preserve the tile's river/coast/features unless asked otherwise. Do not invent a world river/coast or remove existing water/features to fit the layout. No extra model call is required.
";
        static string LegacyRules(bool korean) => korean ? @"
기존 도형 구성 규칙 (정확한 칼데라/분지/좁은 협곡 또는 기존 composite 편집):
- 이것은 기존 composite와 passage의 조합입니다. 새 타입/GL 특징 이름을 만들어 보내지 마세요. 기존 단순 산·호수·도형 요청을 이 구성으로 바꾸거나 요청하지 않은 출구/물/폐허를 추가하지 마세요. 명시한 크기·위치·방향·기존 지형 보존 조건을 우선합니다.
- 칼데라: 바깥 산에서 안쪽을 sub한 닫힌 고리 composite. 마른 내부/정착지 요청이면 fill을 생략한 별도의 e:0.05 내부를 먼저 적용하고 그 위에 고리를 놓습니다. 고리와 내부 평지는 각각 편집 가능한 ID를 사용합니다. 예: 중앙, 바깥 반경0.35, 안쪽 반경0.20, 내부 바닥 반경0.25. 내부 바닥은 고리 밑에만 겹치고 바깥 윤곽을 넘지 않게 합니다. 자연스러움은 산 윤곽에 주고 덮인 내부 바닥에 별도의 불일치하는 굴곡을 주지 마세요. 물/용암 칼데라나 내부 자연물 보존 요청에는 마른 바닥을 강요하지 않습니다.
- 열린 분지: 같은 닫힌 산 고리와 요청한 내부 바닥, 그리고 지정 방향의 별도 passage(scope:mountains)를 조합합니다. 예: 남쪽 출구는 중심→[중심x,0], 동쪽은 중심→[1,중심z]. 폭을 지정하지 않으면8칸을 시작값으로 사용합니다. 고리 자체를 열지 않아야 내부 채움/구조물의 enclosed 참조가 유지됩니다. 자연 윤곽은 명시한 경우에만 추가합니다.
- 좁은 협곡: 실제 산 덩어리를 만든 다음 passage로 관통합니다. 예: 동서 협곡은 중앙 rect 산(w:0.82,h:0.60,e:0.9)과 [[0,0.5],[1,0.5]]의 마른 통로. 넓은 gap의 split은 넓은 골짜기이며 좁은 협곡의 폭을 대신하지 않습니다. 지정 폭은 실제 칸 단위이며 생략 시12칸. 굽은 협곡이면 통로 points를 순서대로 꺾고, 직선이면 일직선을 유지합니다. 산 밖 평지는 보존합니다. 기존 산을 뚫는 요청이면 새 산은 추가하지 않습니다.
- 후속 '안쪽 평지만 넓혀': 고리의 안쪽 경계와 그 아래 내부 바닥을 함께 키우고 바깥 경계·산 윤곽 강도·출구 폭/방향·다른 영역은 유지합니다. 현재 크기를 읽고 산벽이 남을 수 있는 범위로 조절합니다. 내부 바닥을 늘려도 나중에 덮는 고리의 안쪽 경계를 바꾸지 않으면 평지가 넓어지지 않습니다.
- 후속 '분지 전체 이동': 그 분지의 산·내부 바닥·출구를 같은 변위로 옮기고 내부 채움/구조물은 원래 산 ID 참조를 유지합니다. '출구만 다른 방향'은 기존 passage의 points만 변경, '출구를 닫아'는 그 passage만 제거합니다. 고리/바닥/비옥토/폐허를 다시 생성하지 마세요. 특정 분지 전체 삭제는 그 소유 바닥·출구·참조 채움/구조물도 함께 제거하며 다른 분지는 유지합니다.
- 바다 반도/군도, 두꺼운 지붕 동굴, 실제 세계 강의 분기·합류를 이 세 구성으로 대체하지 마세요. 지원 범위와 현재 타일의 월드 연결 조건을 따릅니다.
" : @"
Existing exact recipes (caldera, precise basin with an exit, narrow canyon, or editing existing composites):
- Compose existing composite and passage shapes; do not invent shape types or GL feature names. Do not turn simple mountain/lake/geometric requests into these recipes or add unrequested exits, water or ruins. Explicit size, position, direction and preservation constraints take precedence.
- Caldera: a CLOSED composite mountain ring formed by subtracting an inner shape. For an explicitly dry/buildable interior, apply a separate unpainted e:0.05 floor (omit fill) FIRST and the ring above it. Give floor and ring separate editable IDs. Example center, outer radius0.35, inner radius0.20, floor radius0.25. Overlap the floor beneath the ring without crossing its outer contour. Put requested natural roughness on the mountain; do not give the hidden floor an independent mismatching warp. Do not force a dry floor on a water/lava caldera or a request to preserve interior nature.
- Open basin: use that CLOSED source ring, the requested floor, and a separate passage with scope:mountains in the requested direction. South exit: center→[centerX,0]; east: center→[1,centerZ]. Default width8 cells when unspecified. Do not cut the source ring itself: fills/structures need its enclosed reference. Add natural contours only when requested.
- Narrow canyon: create a real mountain mass, then cut a passage through it. Example east-west: central rect mountain(w:0.82,h:0.60,e:0.9) plus a dry passage [[0,0.5],[1,0.5]]. A split with a broad gap is a wide valley, not a substitute for a narrow canyon's width. Use requested width in cells, default12. Use ordered bends for a winding canyon and collinear points for a straight one. Preserve open ground outside the mountain. If asked to cut an EXISTING mountain, do not add a new mountain mass.
- Follow-up 'enlarge only the interior plain': enlarge the ring's INNER boundary and its floor together, preserving the OUTER boundary, roughness, exit width/direction and unrelated regions. Read current dimensions and retain a mountain wall. Increasing only the floor cannot enlarge the plain under an unchanged ring.
- 'Move the whole basin': move its mountain, floor and exit by the SAME offset; retain source IDs on interior fills/structures. 'Change only exit direction' updates the existing passage points; 'close the exit' removes only that passage. Do not recreate ring/floor/soil/ruins. Deleting one entire basin also removes its own floor, exit and dependent fills/structures, preserving other basins.
- These recipes do not implement ocean peninsulas/archipelagos, thick-roof caves, or branching/merging world rivers. Honor existing capability and world-connection constraints.
";
    }
}
