namespace MapGenAI.MapGen
{
    public static class TextRegionPrompt
    {
        public static string Rules(bool korean) => (korean ? @"
텍스트 영역·재료·위치 지정:
- 복합 요청은 지형/출구/재료의 면적/구조물/유지 조건을 각각 확인한 뒤 하나의 generate.params에 함께 넣습니다. 여러 답변으로 나누거나 마지막 조건만 적용하지 마세요. 의존 대상을 먼저 만들고 해당 ID를 참조합니다. 후속 요청은 현재 상태에서 지정한 ID의 필요한 필드만 수정하며 다른 조건은 다시 만들지 않습니다.
- 고리 산과 그 안쪽의 토양/폐허는 같은 산 ID를 참조하되 region_part:enclosed로 구멍을 선택합니다. 구조물에도 region_part:inside/enclosed를 지원합니다(생략은 기존 inside). 예: structure:{id:inner_ruins,kind:ruin,region:donut_mountain,region_part:enclosed,width:9,height:7,count:2}. 산벽 자체(inside)나 비옥토 70%의 선택 칸을 폐허 영역으로 대신 쓰지 마세요. 그러면 면적비 변경에 따라 폐허가 움직이거나 놓이지 않습니다. 원래 영역이 이동하면 내부 참조도 따라갑니다. region을 해제할 때 region_part도 null로 해제하세요.
- 고리와 출구를 함께 요청하면 닫힌 고리 도형과 별도 passage를 만드세요. 고리 도형 자체에서 출구를 빼면 enclosed가 사라집니다. 통로는 마지막에 산을 깎으며 구조물은 지정 통로 전체를 피합니다. 마른 평지 내부를 명시했다면 산의 안쪽에 별도의 fill 생략/e:0.05 평탄화 영역을 먼저 만들고 고리 산을 그 위에 적용합니다. 원래 자연 장애물을 보존하는 요청에는 내부를 임의로 평탄화하지 마세요. 폭만/비율만/개수만 바꾸는 후속은 각각 passage.width/region_fill.coverage/structure.count만 바꿉니다.
- 중요: 고리를 sub로 만드는 것만으로 구멍의 기존 돌산/물이 없어지지는 않습니다. '안쪽은 마른 평지/정착지'라면 별도 평탄화 영역을 포함하되 토양을 요청하지 않으면 fill은 생략하여 바이옴 바닥을 유지하세요. 기존 강·바다는 보존됩니다. 예: 안쪽 원 반경0.20인 고리 전에 {""id"":""inner_ground"",""type"":""composite"",""shapes"":[{""id"":""ground"",""prim"":""circle"",""center"":[0.5,0.5],""r"":0.24}],""compose"":[{""op"":""add"",""s"":""ground"",""e"":0.05,""f"":0.01}]}를 추가하고, 그 다음 바깥 반경0.35·안쪽 반경0.20 고리 산을 추가합니다. 안쪽 반경보다 약간 넓혀 자연 윤곽 전체를 덮되 산을 나중에 적용합니다. 사각형 등은 해당 내부 형상으로 바꾸세요. region_fill은 비율만 칠하며 자동 평탄화가 아닙니다. 전체 정착지 이동 시 이 평탄화 영역도 함께 이동합니다.
- 이미지 입력/해석/팔레트 기능은 일시 중단입니다. 이미지 요청에는 action:ask로 텍스트 요청을 안내하세요. 저장된 이미지도 생성에 적용되지 않습니다.
- bump/ring/composite fill은 Active fill materials의 정확한 TerrainDef 이름을 지원합니다. 별칭 water/sand/soil/rich_soil/marsh/mud/ice/lava/cooled_lava/gravel/volcanic_rock도 해당 정의가 활성화돼 있으면 가능합니다. lava=LavaDeep(실제 깊은 용암)이며 물로 대체하지 않습니다. LavaShallow는 식는 임시 지형이라 현재 fill 미지원입니다. 미활성 재료는 action:ask로 설명합니다.
- composite의 최상위 fill을 update하면 렌더되는 영역들의 재료가 바뀝니다. 다중 재료 중 일부만 바꾸려면 compose의 해당 fill만 수정하세요. fill:null은 최상위 덮어쓰기를 해제하며 compose의 fill은 유지됩니다.
- 해자 전체의 물을 용암으로 바꾸는 등 재료만 교체할 때는 해당 top-level ID에 changes:{""fill"":""LavaDeep""}만 보냅니다. shapes/compose를 다시 작성하지 마세요. 해자의 구멍·위치·윤곽·높이와 별도 섬/유적은 자동 보존됩니다. 여러 단계의 sub/out/add로 만든 해자도 동일합니다. 다중 재료의 일부 compose만 수정할 때 기존 최상위 fill이 있으면 그 덮어쓰기를 null로 해제해야 내부 fill 변경이 보입니다.
- 마른 협곡·산을 관통하는 통로·출구·평탄한 부지는 composite의 원하는 영역에 fill:soil, e:0.05를 함께 지정합니다. e:0.05는 높이를 조금 더하는 값이 아니라 기존 산을 평지 높이로 깎는 값입니다. fill 없는 음수 e는 호수로 해석되므로 마른 통로에 절대 사용하지 마세요. 통로가 산의 양쪽 바깥까지 닿게 길이를 잡고, 지정한 폭과 방향을 유지하세요. 다른 지형을 지우거나 호수로 대체하지 마세요.
- 예: 왼쪽 산맥을 동서로 관통하는 폭8% 마른 통로 추가 {""action"":""generate"",""params"":{""shape_ops"":[{""op"":""add"",""shape"":{""id"":""west_pass"",""type"":""composite"",""shapes"":[{""id"":""cut"",""prim"":""rect"",""center"":[0.25,0.5],""w"":0.5,""h"":0.08}],""compose"":[{""op"":""add"",""s"":""cut"",""fill"":""soil"",""e"":0.05,""f"":0.01}]}}]}}. 실제 산 범위에 맞춰 길이를 정하고, 자연스러운 윤곽을 요청한 경우에만 edge_roughness를 추가하세요.
- ""도넛/고리 산 안쪽의 70%만 비옥한 토양""처럼 기존 영역의 일부를 재료로 채울 때 반경/높이/비옥도 수치로 비율을 흉내내지 마세요. shape_ops add의 type:region_fill, region:기존 산 ID, region_part:enclosed, coverage:0.7, fill:SoilRich를 사용합니다. enclosed는 고리가 둘러싼 구멍, inside는 기존 영역 자체입니다. 실제 생성 후 산비탈/바위/건물/월드 강·바다/도로를 제외한 칸 수의 비율이며 외부로 번지지 않습니다. 나머지는 원래 지형을 유지합니다. 해당 재료가 이미 요청 비율보다 많으면 나머지를 바꿀 재료를 지정해야 합니다.
- 예: {""shape_ops"":[{""op"":""add"",""shape"":{""id"":""inner_soil"",""type"":""region_fill"",""region"":""central_mountain_donut"",""region_part"":""enclosed"",""coverage"":0.7,""fill"":""SoilRich""}}]}. ID는 현재 상태를 사용하세요. 후속 ""절반만/70%라고 했잖아""는 이 채움 ID의 changes:{""coverage"":0.5} 또는0.7만 수정합니다. 산의 e/strength를 수정하지 마세요. 이전 composite로 잘못 만든 토양은 해당 토양 ID만 remove하고 region_fill을 add하세요.
- region_fill은 소스 영역 이동/윤곽 변경을 따라가며 산 높이를 바꾸지 않습니다. 선택 영역의 중심부부터 채우며 direction:left/right/top/bottom을 지정하면 그 방향부터 채웁니다. 별/하트 등 영역 내부는 inside, 닫힌 고리의 구멍은 enclosed입니다. 닫힌 구멍이 없으면 실패를 알리며 바깥 맵 전체로 대체하지 않습니다. coverage0..1이며0은 추가 채움 없음. 소스 삭제 시 참조 채움도 remove/rebind해야 합니다. 이 채움 ID를 구조물 region으로 참조할 수 있습니다.
- 용암 속 섬: 바깥 원에서 안쪽 원을 sub한 도넛에 fill:lava, 별도 섬 영역에는 fill:soil와 e:0.05(평탄화)를 사용하세요. 내부를 물로 만들지 마세요. 재료가 다른 영역은 서로 다른 top-level id를 사용합니다.
- 위치는 params.structure_ops로 지정합니다. kind:ruin은 지붕·적·전리품 없는 손상된 화강암 벽/바닥 폐허입니다. kind:ancient_danger는 게임의 원래 고대 위협 사원 생성기를 사용합니다. 지붕·내부 시설·동면관·전리품·위험 요소와 경고는 게임 난이도/DLC/무작위 규칙을 따릅니다. 특정 적/전리품 종류와 개수, 퀘스트 단지·임의 모드 구조물은 미지원입니다.
- 고대 위협 위치 예: {""structure_ops"":[{""op"":""add"",""structure"":{""id"":""danger_1"",""kind"":""ancient_danger"",""region"":""island"",""width"":18,""height"":18,""count"":1}}]}. 가로·세로는 각각15~20칸을 명시하고 계획당1~2개/전체최대4개입니다. relation/spacing을 지원합니다. 내부 형상과 방향은 native 생성기가 결정하므로 ancient_danger의 rotation은0만 허용하며 회전 요청에는 ask로 설명하세요. 일반 위험 밀도 danger_density와 위치 지정은 별개입니다. '이곳에만 고대 위협'이면 danger_density:0을 함께 사용하되 다른 랜드마크 위험을 없앤다고 말하지 마세요. 미리보기의 주황 테두리는 예약 면적이며 실제 벽/적/전리품 배치는 완성맵 생성 때 결정됩니다.
- 추가 예: {""structure_ops"":[{""op"":""add"",""structure"":{""id"":""ruins_1"",""kind"":""ruin"",""region"":""island"",""width"":11,""height"":9,""count"":1}}]}. region은 존재하는 top-level bump/ring/composite id입니다. 구멍과 자연스러운 경계를 포함한 실제 내부에 건물 전체 면적이 들어가야 합니다.
- 영역 없이 position:[x,z] 또는 bounds:[서쪽,남쪽,동쪽,북쪽]으로 지정 가능합니다. 좌표0..1, 북쪽z=1. position만 있으면 각 축±0.10 범위에서 찾습니다. region이면 해당 영역 전체에서 찾고 이동한 영역을 따라갑니다. bounds는 추가 제한입니다.
- width/height5..31칸, count1..8, 전체24개. 수정: {""op"":""update"",""id"":""ruins_1"",""changes"":{""count"":2}}. 삭제: {""op"":""remove"",""id"":""ruins_1""}. changes는 position/region/bounds/width/height/count/seed를 지원합니다. position/region/bounds는 null로 해제 가능하나 하나는 필요합니다.
- 참조 영역을 삭제할 때 같은 응답에서 유적도 제거하거나 region을 다시 지정하세요. 위치 지정은 자연 폐허/위협 밀도와 별개입니다. '이곳에만 폐허'라면 ruin_density:0을 함께 사용하되 다른 랜드마크 건물을 없앴다고 말하지 마세요.
- 물·용암·도로·막힌 바위·기존 건물·사용 중 공간에는 배치하지 않습니다. 공간 부족 시 위치 지정 유적은 전부 미생성되고 실패 이유가 표시됩니다. 설정 적용만으로 실제 배치 성공을 단정하지 마세요. 실패 시 영역 확대/평탄화/개수·크기 축소를 제안합니다.
- 구조물 공간 관계: relation:{""target"":""river"",""min_distance"":2,""max_distance"":12,""side"":""east""}는 실제 강의 동쪽에서 가장 가까운 건물 칸까지 거리2~12칸을 요구합니다. target은 river(실제 월드 강)/water(물)/mountain(실제 산 바위)/region_edge(지정 region의 안쪽 가장자리), side는 any/north/south/east/west입니다. 산기슭/강가 요청은 이 relation으로 표현하고 임의 좌표로 대신하지 마세요. 없는 지형은 자동 생성하지 않으며 조건 실패를 안내합니다.
- 섬 가장자리 요청은 region ID와 relation:{""target"":""region_edge"",""min_distance"":2,""max_distance"":8}을 함께 사용합니다. 전체 건물은 영역 안에 유지됩니다. relation만으로도 위치 기준을 지정할 수 있고 position/bounds/region이 함께 있으면 모두 만족해야 합니다. 거리0~64칸, max_distance>=min_distance. relation을 update하면 객체 전체를 교체하므로 기존 조건을 유지할 땐 포함하세요. relation:null은 관계를 해제합니다.
- rotation은0/90/180/270도, spacing은 구조물 사이 최소 빈칸 수1~60(기본1)입니다. 강을 따라 떨어뜨려 배치할 때 relation과 spacing을 함께 사용합니다. 최소 간격은 정확히 같은 간격이나 강 양쪽 동일 개수 배치가 아닙니다. 양쪽에 필요하면 east/west 등 계획을 별도로 만드세요. changes에도 relation/rotation/spacing을 사용할 수 있습니다.
" : @"
Text regions, materials and positioned structures:
- For a compound request, account for terrain, access routes, material fractions, structures and preservation constraints in ONE generate.params. Do not split it across replies or apply only the final clause. Create dependencies first, then reference their IDs. Follow-ups edit only the requested fields on existing IDs, preserving the other conditions.
- A ring mountain's interior soil and ruins reference the SAME mountain ID with region_part:enclosed. Structures also support region_part:inside/enclosed (omitted retains legacy inside). Example: structure:{id:inner_ruins,kind:ruin,region:donut_mountain,region_part:enclosed,width:9,height:7,count:2}. Do not use the rocky ring itself (inside) or the selected 70% soil cells as the ruins' region: changing coverage would move or prevent the ruins. Interior references follow source movement. When clearing region also clear region_part with null.
- For a ring plus exit, keep a CLOSED source ring and add a SEPARATE passage. Subtracting the exit from the source ring destroys its enclosed interior. Passages cut mountains last; positioned structures avoid their entire route. When a dry flat interior is explicitly requested, first add a separate unpainted e:0.05 interior region, then apply the mountain ring above it. Do not flatten natural obstacles when asked to preserve them. Width-only/fraction-only/count-only follow-ups edit only passage.width/region_fill.coverage/structure.count respectively.
- IMPORTANT: subtracting a hole does NOT remove pre-existing rock/water there. A requested dry flat/buildable interior needs its own flattening region; omit fill to retain biome ground unless a material was requested. Existing rivers/oceans stay protected. Example before a ring with inner radius0.20: add {""id"":""inner_ground"",""type"":""composite"",""shapes"":[{""id"":""ground"",""prim"":""circle"",""center"":[0.5,0.5],""r"":0.24}],""compose"":[{""op"":""add"",""s"":""ground"",""e"":0.05,""f"":0.01}]}, THEN the ring mountain of outer radius0.35/inner radius0.20. Slightly overlap the inner contour so a natural outline stays dry; apply the mountain afterward. Adapt to rectangular or other interiors. region_fill controls material fraction, not flattening. Move this ground region too when moving the whole settlement.
- Image input, interpretation and palette generation are paused. For image requests use action:ask and suggest text. Stored image data is inactive.
- bump/ring/composite fill accepts exact names from Active fill materials. Aliases water/sand/soil/rich_soil/marsh/mud/ice/lava/cooled_lava/gravel/volcanic_rock require loaded definitions. lava means real LavaDeep, never water. Temporary cooling LavaShallow is unsupported. Explain unavailable materials with action:ask.
- Updating top-level composite fill overrides rendered regions. For one material in a multi-material composite update only its compose fill. Top-level fill:null removes that override, retaining compose fills.
- For a material-only replacement of a whole moat, update only its top-level ID with changes:{""fill"":""LavaDeep""}. Do not rewrite shapes/compose. Holes, position, contour, height and separate islands/structures are preserved automatically, including a multi-step sub/out/add chain. When changing only part of a multi-material compose, clear an existing top-level fill with null so it does not mask the internal edit.
- Dry canyons, mountain passages, exits and flat building sites use a composite region with BOTH fill:soil and e:0.05. This is an absolute flat elevation target, not a small added hill. Negative e without fill means a lake: NEVER use it for a dry passage. Extend the cut beyond both sides of the mountain, preserving the requested width/direction and unrelated terrain.
- Example west mountain east-west dry passage, width8%: {""action"":""generate"",""params"":{""shape_ops"":[{""op"":""add"",""shape"":{""id"":""west_pass"",""type"":""composite"",""shapes"":[{""id"":""cut"",""prim"":""rect"",""center"":[0.25,0.5],""w"":0.5,""h"":0.08}],""compose"":[{""op"":""add"",""s"":""cut"",""fill"":""soil"",""e"":0.05,""f"":0.01}]}}]}}. Adjust length to the actual mountain extent; add edge_roughness only for an explicitly natural outline.
- For a fraction of an existing region (e.g. rich soil in 70% of a donut mountain interior), NEVER approximate the percentage with radius/height/fertility. Add type:region_fill with region:existing terrain ID, region_part:enclosed, coverage:0.7, fill:SoilRich. enclosed means the hole surrounded by a closed ring; inside means the source region itself. Counts eligible cells after generation, excluding mountain slopes/rocks/buildings/world rivers/oceans/roads, with no outward feathering. Preserve the remainder. If the material already exceeds the fraction, a replacement for the remainder must be specified.
- Example: {""shape_ops"":[{""op"":""add"",""shape"":{""id"":""inner_soil"",""type"":""region_fill"",""region"":""central_mountain_donut"",""region_part"":""enclosed"",""coverage"":0.7,""fill"":""SoilRich""}}]}. Use actual state IDs. Follow-up ""only half/I said70%"" updates ONLY that fill ID's coverage to0.5/0.7, never the mountain's e/strength. Replace an older wrongly-sized composite soil by removing ONLY that soil ID and adding region_fill.
- region_fill follows source moves/contours without changing mountain heights. Fills the deepest interior first; optional direction:left/right/top/bottom starts from that side. Stars/hearts use inside, closed-ring holes use enclosed. Missing enclosed space fails explicitly, never fills the exterior map. coverage0..1; zero adds no material. Remove/rebind dependent fills when removing a source. Structures can reference the fill ID as their region.
- Island in lava: subtract an inner circle from the outer circle; fill the annulus with lava. Use a separate soil island region with e:0.05 to flatten it. Give distinct top-level IDs to separate material regions.
- params.structure_ops controls position, not density. kind:ruin makes damaged granite walls/floors without roof, enemies or loot. kind:ancient_danger uses the native ancientTemple generator with its roof/interior/caskets/loot/threats/warning rules, respecting difficulty, DLC and randomness. Specific enemy/loot counts/types, quest complexes and arbitrary mod structures are unsupported.
- Ancient danger example: {""structure_ops"":[{""op"":""add"",""structure"":{""id"":""danger_1"",""kind"":""ancient_danger"",""region"":""island"",""width"":18,""height"":18,""count"":1}}]}. Explicit width/height15..20 cells, count1..2 per plan, maximum4 total. relation/spacing supported. Native generation controls interior orientation; ancient_danger accepts rotation:0 only. Explain rotation requests with ask. Position is independent from random danger_density. For dangers only here use danger_density:0 without claiming other landmark threats are removed. The orange preview outline is reserved space; actual walls/enemies/loot are generated in the full map.
- Add: {""structure_ops"":[{""op"":""add"",""structure"":{""id"":""ruins_1"",""kind"":""ruin"",""region"":""island"",""width"":11,""height"":9,""count"":1}}]}. region references an existing top-level composite/bump/ring ID. The full footprint must fit inside its actual mask, including holes and natural edges.
- Alternatively position:[x,z] or bounds:[west,south,east,north], normalized0..1, north=z1. A point searches within ±0.10 per axis. A region searches its entire interior and follows region moves. Optional bounds further restrict placement.
- Width/height5..31 cells, count1..8, total24. Update: {""op"":""update"",""id"":""ruins_1"",""changes"":{""count"":2}}. Remove: {""op"":""remove"",""id"":""ruins_1""}. Changes accept position/region/bounds/width/height/count/seed. position/region/bounds may be null, but at least one is required.
- Removing a referenced shape requires removing/rebinding its structures in the same response. Position does not affect random ruin/danger density. For ruins only here use ruin_density:0 too, without claiming it removes other landmark buildings.
- No placement on water/lava/roads/blocked rocks/buildings/used space. If any footprint cannot fit, no positioned structures spawn and generation reports failure. Settings applied does not mean placement succeeded. Suggest a larger/flatter region or fewer/smaller ruins.
- Spatial relation: relation:{""target"":""river"",""min_distance"":2,""max_distance"":12,""side"":""east""} requires the closest footprint cell to be 2..12 cells from the actual river, on its east side. Targets: river (world river), water, mountain (solid mountain rock), region_edge (inner boundary of the specified region). Sides: any/north/south/east/west. Use relations for riverbank/foothill requests, not guessed coordinates. Missing target terrain causes an explicit failure, never automatic terrain creation.
- For an island edge use region plus relation:{""target"":""region_edge"",""min_distance"":2,""max_distance"":8}. The entire footprint stays inside the region. Relation alone may locate a structure; any supplied position/bounds/region also applies. Distances are integer cells0..64, max>=min. Updating relation replaces the whole object; retain its other conditions when needed. relation:null clears it.
- rotation accepts0/90/180/270 degrees. spacing is minimum empty cells between footprints1..60 (default1). Combine relation and spacing for separated structures along a river. It does not guarantee exact equal intervals or equal counts on both banks; use separate east/west plans for both sides. Changes also accept relation/rotation/spacing.
") + "\nActive fill materials (loaded natural permanent terrain only):\n" + TerrainMaterials.Catalog();
    }
}
