namespace MapGenAI.MapGen
{
    public static class TextRegionPrompt
    {
        // Shared technical vocabulary; Dialog supplies the response language.
        // Keep the loaded catalog intact, including mod terrain names.
        public static string Rules(bool korean) => @"
Text regions, materials and structures:
- Compound requests: include terrain, access, material fractions, structures and preservation constraints in ONE generate.params. Create dependencies before references. Follow-ups patch only requested fields of existing IDs.
- region_part accepts ONLY inside|enclosed, for both region_fill and structures; never outside/border. Ring interiors: soil and ruins reference the mountain ID with region_part:enclosed (closed hole), not inside (rocky ring) or a fractional soil mask. Structures default to inside. Keep the source ring CLOSED and cut exits with a separate passage, which cuts last and excludes structures along its entire route. Clearing region also clears region_part:null.
- Subtracting a hole leaves pre-existing rock/water. For an explicitly dry/buildable interior, add a separate composite ground region FIRST, compose e:0.05,f:0.01, slightly wider than the inner contour; then apply the ring above it. Omit fill unless soil is requested, preserving biome ground and protected rivers/oceans. Move this ground with the whole settlement. Do not flatten obstacles requested to remain; region_fill does not flatten.
- Image input/interpretation/palette are paused, including saved images; answer image requests with action:ask suggesting text.
- bump/ring/composite fill: use loaded Active fill materials or aliases water/sand/soil/rich_soil/marsh/mud/ice/lava/cooled_lava/gravel/volcanic_rock. lava=LavaDeep, NEVER water. Temporary LavaShallow is unsupported; unavailable materials require ask.
- Material-only replacement: update the existing top-level ID with changes:{""fill"":""LavaDeep""}, preserving shapes/compose, holes, outline, elevation, islands and structures, even for sub/out/add chains. Top-level composite fill overrides compose fills; fill:null removes only that override. To change one internal material, edit its compose fill and clear any masking top-level fill.
- Dry composite cuts use e:0.05 (absolute flat height) plus fill:soil, extending beyond both mountain sides at the requested width/direction. NEVER use negative e without fill for dry cuts: it means water. Prefer passage for explicit connectivity/cell width. Natural outlines require edge_roughness only when requested. Lava islands use a lava annulus (outer minus inner) and a separate soil island with e:0.05; distinct materials need distinct top-level IDs.
- Fractional material example: {""shape_ops"":[{""op"":""add"",""shape"":{""id"":""inner_soil"",""type"":""region_fill"",""region"":""mountain_id"",""region_part"":""enclosed"",""coverage"":0.7,""fill"":""SoilRich""}}]}. Use actual state IDs. NEVER approximate 70% by radius, elevation, strength or fertility. Follow-up 'only half/I said70%' changes ONLY coverage; width-only/count-only edits similarly change passage.width/structure.count. Replace a wrong composite soil by removing only that soil ID and adding region_fill.
- region_fill: coverage0..1 (0 adds nothing), inside for stars/hearts/source area, enclosed for closed-ring holes. Fraction counts eligible generated cells excluding slopes/rocks/buildings/world rivers/oceans/roads; no outward feathering, remainder preserved. If existing material already exceeds coverage, specify a replacement for the remainder. Fills deepest interior first or direction:left/right/top/bottom. Follows source moves/contours without altering heights. Missing enclosure fails, never uses the exterior map. Source removal requires removing/rebinding dependent fills/structures. Structures may reference a fill ID if that selected area is intended.
- Position via structure_ops, independently of density. Add: {""structure_ops"":[{""op"":""add"",""structure"":{""id"":""ruins"",""kind"":""ruin"",""region"":""island"",""width"":11,""height"":9,""count"":1}}]}. Update {op:update,id:ruins,changes:{count:2}}; remove {op:remove,id:ruins}. Changes accept position/region/region_part/bounds/width/height/count/seed/relation/rotation/spacing.
- kind:ruin = damaged granite walls/floors, no roof/enemies/loot; width/height5..31 cells, count1..8, total24. kind:ancient_danger = native ancientTemple including roof/interior/caskets/loot/threat/warning under difficulty/DLC/random rules; explicitly set width/height15..20, count1..2 per plan, total4, rotation:0 ONLY (ask on rotation requests). Specific enemies/loot/counts, quest complexes and arbitrary mod structures unsupported. Orange preview outline reserves space; full generation determines contents. For 'only here' also set ruin_density:0 or danger_density:0; never claim removal of other landmark buildings/threats.
- Location: region references a top-level bump/ring/composite (or region_fill) ID and follows moves. Entire footprint must fit its actual mask including holes/natural edges. Alternatively position:[x,z] searches +/-0.10 per axis; bounds:[west,south,east,north] restricts placement, coordinates0..1/north z1. position/region/bounds can be null; retain a location constraint (relation alone also works).
- relation:{""target"":""river"",""min_distance"":2,""max_distance"":12,""side"":""east""} measures nearest footprint cell, integer distances0..64/max>=min. Targets river(actual world river)/water/mountain(solid rock)/region_edge(inner boundary of specified region); side:any/north/south/east/west. Use relation for banks/foothills, not guessed coordinates. Island edge needs region+region_edge relation; full footprint stays inside. All supplied location constraints apply. Missing target fails without creating terrain. Updating relation replaces the WHOLE object; null clears it.
- rotation:0/90/180/270 (ancient_danger only0). spacing:1..60 empty cells, default1. Minimum separation does not guarantee equal intervals/counts on both banks; use separate east/west plans. No placement on water/lava/roads/blocked rock/buildings/used space. Any failed footprint prevents all positioned structures; report failure and suggest larger/flatter region or fewer/smaller structures. Accepted settings do not prove placement success.
" + "\nActive fill materials (loaded natural permanent terrain only):\n" + TerrainMaterials.Catalog();
    }
}
